import 'package:get/get.dart';
import 'package:flutter/material.dart';
import '../../core/services/secure_storage_service.dart';
import '../../core/utils/json_parser.dart';

class LanguageController extends GetxController {
  Locale _locale = const Locale('ar');

  LanguageController();

  @override
  void onInit() {
    super.onInit();
    _loadLanguage();
  }
  Future<void> _loadLanguage() async {
    final storedLanguage = await SecureStorageService.instance.readLanguage();
    final lang = storedLanguage == 'en' ? 'en' : 'ar';

    JsonParser.currentLanguage = lang;
    _locale = Locale(lang);

    update();
  }

  Locale get locale => _locale;
  String get languageCode => _locale.languageCode;
  bool get isArabic => _locale.languageCode == 'ar';
  bool get isEnglish => _locale.languageCode == 'en';

  Future<void> setArabic() async {
    JsonParser.currentLanguage = 'ar';

    _locale = const Locale('ar');

    await SecureStorageService.instance.saveLanguage('ar');

    update();
  }

  Future<void> setEnglish() async {
    JsonParser.currentLanguage = 'en';

    _locale = const Locale('en');

    await SecureStorageService.instance.saveLanguage('en');

    update();
  }

  Future<void> toggle() async {
    if (isArabic) {
      await setEnglish();
    } else {
      await setArabic();
    }
  }

  String t(String key, [Map<String, Object?> params = const {}]) {
    var value = AppStrings.of(_locale.languageCode)[key] ?? key;
    for (final entry in params.entries) {
      value = value.replaceAll('{${entry.key}}', '${entry.value ?? ''}');
    }
    return value;
  }
}

class AppStrings {
  static Map<String, String> of(String lang) => lang == 'en' ? _en : _ar;

  static const _ar = {
    // General
    'app_name': 'البيرق هايبر ماركت',
    'save': 'حفظ',
    'cancel': 'إلغاء',
    'delete': 'حذف',
    'edit': 'تعديل',
    'close': 'إغلاق',
    'confirm': 'تأكيد',
    'search': 'بحث',
    'loading': 'جاري التحميل...',
    'error': 'خطأ',
    'success': 'تم بنجاح',
    'no_data': 'لا توجد بيانات',
    'retry': 'إعادة المحاولة',
    // Auth
    'login': 'تسجيل الدخول',
    'logout': 'تسجيل الخروج',
    'register': 'إنشاء حساب',
    'phone': 'رقم الهاتف',
    'email': 'البريد الإلكتروني',
    'password': 'كلمة المرور',
    'login_with_phone': 'الدخول برقم الهاتف',
    'login_with_email': 'الدخول بالبريد الإلكتروني',
    'otp_title': 'رمز التحقق',
    'otp_sent_phone': 'تم إرسال رمز التحقق إلى',
    'otp_sent_email': 'تم إرسال رمز التحقق إلى بريدك',
    'resend': 'إعادة الإرسال',
    'no_account': 'ليس لديك حساب؟',
    // Home
    'home': 'الرئيسية',
    'categories': 'الأقسام',
    'cart': 'السلة',
    'profile': 'حسابي',
    'favorites': 'المفضلة',
    'orders': 'طلباتي',
    'notifications': 'الإشعارات',
    // Product
    'add_to_cart': 'إضافة للسلة',
    'add_to_favorites': 'إضافة للمفضلة',
    'remove_from_favorites': 'إزالة من المفضلة',
    'unit': 'الوحدة',
    'price': 'السعر',
    'quantity': 'الكمية',
    'in_stock': 'متوفر',
    'out_of_stock': 'غير متوفر',
    'select_unit': 'اختر الوحدة',
    // Cart
    'cart_empty': 'السلة فارغة',
    'subtotal': 'المجموع الجزئي',
    'delivery_fee': 'رسوم التوصيل',
    'total': 'الإجمالي',
    'checkout': 'إتمام الطلب',
    'clear_cart': 'تفريغ السلة',
    // Checkout
    'delivery_address': 'عنوان التوصيل',
    'payment_method': 'طريقة الدفع',
    'coupon': 'كوبون الخصم',
    'place_order': 'تأكيد الطلب',
    'order_summary': 'ملخص الطلب',
    // Orders
    'order_number': 'رقم الطلب',
    'order_status': 'حالة الطلب',
    'track_order': 'تتبع الطلب',
    // Address
    'add_address': 'إضافة عنوان',
    'delivery_addresses': 'عناوين التوصيل',
    'default_address': 'افتراضي',
    // Admin
    'manage_products': 'إدارة المنتجات',
    'manage_orders': 'إدارة الطلبات',
    'manage_users': 'إدارة المستخدمين',
    'manage_delivery': 'إدارة التوصيل',
    'reports': 'التقارير',
    'total_sales': 'إجمالي المبيعات',
    'total_orders': 'إجمالي الطلبات',
    'active_users': 'المستخدمون النشطون',
    'pending_orders': 'الطلبات المعلقة',
    // Delivery
    'my_deliveries': 'توصيلاتي',
    'current_order': 'الطلب الحالي',
    'delivery_history': 'سجل التوصيل',
    'start_delivery': 'بدء التوصيل',
    'complete_delivery': 'إتمام التوصيل',
    // Settings
    'settings': 'الإعدادات',
    'dark_mode': 'الوضع الليلي',
    'language': 'اللغة',
    'arabic': 'العربية',
    'english': 'الإنجليزية',
    // Info
    'about_us': 'من نحن',
    'contact_us': 'اتصل بنا',
    'faq': 'الأسئلة الشائعة',
    'privacy_policy': 'سياسة الخصوصية',
    'terms': 'شروط الاستخدام',
    'added_to_cart': 'تمت إضافته إلى السلة',
    'appearance': 'المظهر والواجهة',
    'account': 'الحساب',
    'information': 'معلومات',
    'app_version': 'إصدار التطبيق',
    'enabled': 'مفعّل',
    'disabled': 'معطّل',
    'delivery_driver': 'سائق التوصيل',
    'loading_products': 'جاري تحميل المنتجات...',
    'products_load_error_title': 'تعذر تحميل المنتجات',
    'network_retry': 'تحقق من اتصالك بالإنترنت وأعد المحاولة',
    'no_products': 'لا توجد منتجات حالياً',
    'products_coming_soon': 'سيتم إضافة منتجات قريباً',
    'products_refresh_stale': 'تعذر تحديث المنتجات — تعرض بيانات قديمة',
    'refresh': 'تحديث',
    'hello': 'مرحبًا',
    'guest': 'زائر',
    'search_product_hint': 'ابحث عن أي منتج...',
    'reports_load_error': 'تعذر تحميل التقارير',
    'system_summary': 'ملخص النظام',
    'from_date': 'من تاريخ',
    'to_date': 'إلى تاريخ',
    'customers': 'العملاء',
    'locations': 'المواقع',
    'pending': 'قيد الانتظار',
    'confirmed': 'مؤكد',
    'processing': 'قيد التجهيز',
    'shipped': 'تم الشحن',
    'delivered': 'تم التسليم',
    'cancelled': 'ملغي',
    'orders_value': 'قيمة الطلبات',
    'drivers_performance': 'أداء المندوبين',
    'no_driver_data': 'لا توجد بيانات للمندوبين',
    'view_details': 'عرض التفاصيل',
    'cart_changed_coupon': 'تغيرت محتويات السلة، يرجى إعادة التحقق من الكوبون.',
    'coupon_expired': 'انتهت صلاحية الكوبون',
    'please_wait_order': 'يُرجى الانتظار حتى اكتمال إرسال الطلب...',
    'change_or_add_address': 'تغيير أو إضافة عنوان',
    'no_address': 'لا يوجد عنوان',
    'add_delivery_address_hint': 'أضف عنوان التوصيل لإكمال الطلب',
    'add_delivery_address': 'إضافة عنوان توصيل',
    'enter_coupon': 'أدخل كود الخصم',
    'apply': 'تطبيق',
    'cart_changed_reapply_coupon': 'تغيرت قيمة السلة، أعد تطبيق الكوبون للتحقق من الخصم.',
    'order_details': 'تفاصيل الطلب',
    'payment_status': 'حالة الدفع',
    'address': 'العنوان',
    'notes': 'ملاحظات',
    'gift': 'هدية',
    'product_unavailable': 'منتج غير متوفر',
    'unknown': 'غير معروف',
    'coupon_discount': 'خصم الكوبون',
    'no_orders': 'لا توجد طلبات',
    'loading_orders': 'جاري تحميل الطلبات...',
    'no_notifications': 'لا توجد إشعارات',
    'no_notifications_current': 'لا توجد إشعارات حالياً',
    'barcode_scanner': 'ماسح الباركود',
    'point_camera_barcode': 'وجّه الكاميرا نحو باركود المنتج',
    'searching_product': 'جاري البحث عن المنتج...',
    'enter_barcode_manual': 'إدخال الباركود يدويًا',
    'search_product': 'بحث عن المنتج',
    'scanner_camera_error': 'تعذر تشغيل كاميرا المسح. يمكنك إدخال الباركود يدويًا.',
    'increase_quantity': 'زيادة الكمية',
    'decrease_quantity': 'إنقاص الكمية',
    'no_units_product': 'لم يتم ربط وحدات بهذا المنتج بعد.',
    'product_unavailable_purchase': 'هذا المنتج غير متاح للشراء حالياً',
    'favorites_empty': 'المفضلة فارغة',
    'clear_cart_confirm': 'هل تريد حذف جميع المنتجات؟',
    'logout_confirm': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
      'no_addresses': 'لا يوجد أي عنوان',
    'add_first_address': 'أضف عنوانك الأول لإتمام الطلب',
    'delete_address': 'حذف العنوان',
    'delete_address_confirm': 'هل تريد حذف هذا العنوان نهائياً؟',
    'address_deleted': 'تم حذف العنوان بنجاح',
    'address_delete_failed': 'فشل حذف العنوان، حاول مرة أخرى',
    'set_default': 'تعيين افتراضي',
    'address_name': 'اسم العنوان',
    'edit_address': 'تعديل عنوان',
    'password_required': 'كلمة المرور مطلوبة',
    'smart_shopping_tagline': 'تسوق ذكي • توصيل سريع',
    'welcome_login': 'مرحباً بك! سجّل دخولك للمتابعة',
    'show_password': 'إظهار كلمة المرور',
    'hide_password': 'إخفاء كلمة المرور',
    'create_account_new': 'إنشاء حساب جديد',
    'register_subtitle': 'أدخل بياناتك لإنشاء حساب والبدء في التسوق',
    'confirm_password_required': 'تأكيد كلمة المرور مطلوب',
    'passwords_mismatch': 'كلمتا المرور غير متطابقتين',
    'full_name': 'الاسم الكامل',
    'confirm_password': 'تأكيد كلمة المرور',
    'loading_cart': 'جاري تحميل السلة...',
    'cart_load_error': 'تعذر تحميل السلة',
    'clear': 'تفريغ',
    'add_products_home': 'أضف منتجات من الصفحة الرئيسية',
    'shop_now': 'تسوق الآن',
    'total_products': 'إجمالي المنتجات',
    'continue_checkout': 'متابعة إتمام الطلب',
    'free_gift': 'هدية مجانية',
    'loading_categories': 'جاري تحميل الأقسام...',
    'categories_load_error': 'تعذر تحميل الأقسام',
    'no_categories': 'لا توجد أقسام',
    'categories_coming_soon': 'سيتم إضافة الأقسام قريباً',
    'offers': 'العروض',
    'order_notes': 'ملاحظات الطلب',
    'order_notes_hint': 'اكتب أي ملاحظات حول الطلب...',
    'delivery_fee_at_order': 'تُحدد عند إنشاء الطلب',
    'final_total_in_details': 'سيتم عرض الإجمالي النهائي في تفاصيل الطلب',
    'my_earnings': 'أرباحي',
    'today': 'اليوم',
    'week': 'الأسبوع',
    'month': 'الشهر',
    'deliveries': 'التوصيلات',
    'last_7_days': 'آخر 7 أيام',
    'history': 'السجل',
    'order_updated': 'تحديث الطلب',
    'confirmed_status': 'تم التأكيد',
    'out_for_delivery': 'خرج للتوصيل',
    'unspecified': 'غير محددة',
    'delivered_feminine': 'مُسلَّمة',
    'cancelled_feminine': 'ملغاة',
    'no_delivery_history': 'لا يوجد سجل توصيل',
    'new_order': 'طلب جديد',
    'new_order_available': 'وصل طلب جديد متاح للتوصيل',
    'new_orders_available': 'وصلت طلبات جديدة متاحة للتوصيل',
    'driver': 'السائق',
    'available_orders': 'طلبات متاحة',
    'no_available_orders': 'لا توجد طلبات متاحة حالياً',
    'no_active_deliveries': 'ليس لديك طلبات قيد التوصيل',
    'hello_user': 'مرحباً، {name}',
    'order': 'طلب',
    'addresses': 'عناوين',
    'support_info': 'الدعم والمعلومات',
    'logout_confirm_account': 'هل تريد تسجيل الخروج من حسابك؟',
    'exit': 'خروج',
    'current_stage': 'المرحلة الحالية',
    'order_cancelled': 'تم إلغاء الطلب',
    'search_error': 'تعذر تنفيذ البحث',
    'loading_product': 'جاري تحميل المنتج...',
    'product_load_error': 'تعذر تحميل المنتج',
    'best_price': 'أفضل سعر',
    'item_number': 'رقم الصنف',
    'unit_barcode': 'باركود الوحدة',
    'category': 'القسم',
    'status': 'الحالة',
    'product_description': 'وصف المنتج',
    'quantity_hint': 'يمكنك زيادة أو تقليل الكمية',
    'related_products': 'منتجات ذات صلة',
    'order_received': 'تم استلام طلبك! 🎉',
    'order_contact_hint': 'سيتم التواصل معك لتأكيد طلبك وتحديد موعد التوصيل',
    'what_happens_now': 'ماذا يحدث الآن؟',
    'store_receives_order': 'المتجر يستلم طلبك',
    'preparing_products': 'يتم تجهيز المنتجات',
    'delivery_to_door': 'التوصيل لباب بيتك',
    'back_home': 'العودة للرئيسية',
    'select_location_confirm': 'حدد موقعك ثم اضغط تأكيد الموقع',
    'selected_map_location': 'موقع محدد على الخريطة',
    'choose_location': 'اختيار الموقع',
    'resolving_address': 'جارٍ تحديد العنوان...',
    'confirm_location': 'تأكيد الموقع',
    'see_coupons_offers': 'شوف الكوبونات بعروضها',
    'unit_not_selected': 'لم يتم اختيار وحدة',
    'generic_error': 'حدث خطأ، حاول مرة أخرى',
    'sort_default': 'الترتيب الافتراضي',
    'price_low_high': 'السعر: من الأقل',
    'price_high_low': 'السعر: من الأعلى',
    'name': 'الاسم',
    'search_in_category': 'ابحث في القسم',
    'offers_load_error': 'تعذر تحميل العروض',
    'no_offers': 'لا توجد عروض',
    'pull_more_offers': 'اسحب للأعلى للبحث عن المزيد من العروض',
    'no_products_category': 'لا توجد منتجات في هذا القسم حالياً',
    'no_data_available': 'لا توجد بيانات متاحة حاليًا',
    'added_product_dynamic': 'تمت إضافة {product}',
    'discount': 'خصم',
    'order_number_dynamic': 'طلب #{number}',
    'order_number_dynamic2': 'رقم الطلب: {number}',
    'order_number_widget': 'رقم الطلب: #{number}',
    'product_added_dynamic': 'تمت إضافة {product} × {quantity} إلى السلة',
    'products': 'المنتجات',
    'sales': 'المبيعات',
    'special_offer': 'عرض خاص',
    'invalid_coupon': 'الكوبون غير صالح',
    'coupon_applied': 'تم تطبيق الكوبون ✓',
    'coupon_applied_dynamic': 'تم تطبيق الكوبون، الخصم {amount} ر.ي',
    'order_create_failed': 'فشل إنشاء الطلب، حاول مرة أخرى',
    'order_submit_failed': 'فشل إرسال الطلب',
    'order_submit_error': 'حدث خطأ أثناء إرسال الطلب، حاول مرة أخرى.',
    'default': 'افتراضي',
    'choose_location_map': 'اختيار الموقع من الخريطة',
    'default_address_title': 'عنوان افتراضي',
    'favorites_load_error': 'تعذر تحميل المفضلة',
    'favorites_hint': 'اضغط على قلب أي منتج لإضافته هنا',
    'search_product_hint_short': 'ابحث عن منتج...',
    'search_product_or_barcode': 'جرّب البحث باسم المنتج أو الباركود.',
    'start_search': 'ابدأ بكتابة اسم المنتج',
    'search_by_name_barcode_category': 'يمكنك البحث بالاسم أو الباركود أو القسم',
    'clear_all': 'مسح الكل',
    'search_product_short': 'ابحث عن منتج',
    'no_results': 'لا توجد نتائج',
    'no_search_results_query': 'لم نعثر على "{query}"\nجرّب البحث باسم آخر أو بالباركود أو باسم القسم.',
    'favorites_load_error_retry': 'تعذر تحميل المفضلة. حاول مرة أخرى.',
    'loading_favorites': 'جاري تحميل المفضلة...',
    'favorites_added_count': 'تمت إضافة {count} منتج للسلة',
    'move_all_to_cart': 'نقل الكل للسلة',
    'search_error_retry': 'تعذر تنفيذ البحث. حاول مرة أخرى.',
    'updating_cart': 'جاري التحديث...',
    'cart_updated': 'تم تحديث السلة',
    'products_load_error': 'حدث خطأ أثناء تحميل المنتجات',
    'available_orders_load_error': 'تعذر تحميل الطلبات المتاحة',
    'my_deliveries_load_error': 'تعذر تحميل طلباتك',
    'deliveries_refresh_error': 'تعذر تحديث الطلبات',
    'action_in_progress': 'يوجد إجراء قيد التنفيذ',
    'claim_order_error': 'تعذر استلام الطلب',
    'order_status_update_error': 'تعذر تحديث حالة الطلب',
    'order_details_load_error': 'تعذر تحميل تفاصيل الطلب',
    'invalid_updated_order_data': 'بيانات الطلب بعد التحديث غير صالحة',
    'invalid_order_data': 'بيانات الطلب غير صالحة',
    'invalid_barcode': 'يرجى إدخال رمز باركود صالح',
    'no_product_for_barcode': 'لم يتم العثور على أي منتج مرتبط بالرمز: {barcode}',
    'no_unit_for_barcode': 'لم يتم العثور على وحدة مرتبطة بالرمز: {barcode}',
    'product_search_error_retry': 'حدث خطأ أثناء البحث عن المنتج. يرجى المحاولة مجددًا.',
    'no_product_for_barcode_generic': 'لم يتم العثور على منتج بهذا الباركود',
    'orders_load_error_retry': 'تعذر تحميل الطلبات. حاول مرة أخرى.',
    'categories_load_error_retry': 'تعذر تحميل الأقسام. حاول مرة أخرى.',
    'ads_load_error': 'حدث خطأ أثناء تحميل الإعلانات',
    'products_load_error_retry': 'تعذر تحميل المنتجات. حاول مرة أخرى.',
    'login_required_action': 'يجب تسجيل الدخول لإتمام هذه العملية.',
    'add_address_error': 'فشلت عملية إضافة العنوان',
    'edit_address_error': 'فشلت عملية تعديل العنوان',
    'copy_number': 'نسخ الرقم',
    'call': 'اتصال',
    'copy_address': 'نسخ العنوان',
    'open_maps': 'فتح الخرائط',
    'app_version_full': 'البيرق هايبر ماركت v1.0.0',
    'user': 'المستخدم',
    'already_have_account': 'لديك حساب بالفعل؟  ',
    'scan_barcode': 'مسح باركود',
    'street': 'الشارع',
    'recent_searches': 'عمليات البحث الأخيرة',
    'products_count': '{count} منتج',
    'orders_count': '{count} طلب',
    'select_products': 'اختيار المنتجات',
    'selected_count': '{count} محدد',
    'select_at_least_one_unit': 'اختر وحدة واحدة على الأقل',
    'confirm_selection_count': 'تأكيد الاختيار ({count})',
    'available_units_count': '{count} وحدة متاحة',
    'quantity_value': 'الكمية: {quantity}',
    'cash_payment': 'الدفع نقداً',
    'bank_card_payment': 'بطاقة بنكية',
    'today_special_offer': 'عرض خاص اليوم!',
    'today_offer_body': 'خصم 20% على جميع منتجات الألبان حتى نهاية اليوم.',
    'order_shipped_notification': 'تم شحن طلبك',
    'order_out_for_delivery_body': 'طلبك رقم #1042 خرج للتوصيل الآن.',
    'login_error_retry': 'تعذر تسجيل الدخول. حاول مرة أخرى.',
    'register_error_retry': 'تعذر إنشاء الحساب. حاول مرة أخرى.',
    'enter_coupon_first': 'أدخل كود الكوبون أولاً',
    'coupon_validation_error': 'تعذر التحقق من الكوبون',
    'cart_must_have_product': 'يجب إضافة منتج واحد على الأقل',
    'order_submission_in_progress': 'يوجد طلب قيد الإرسال',
    'invalid_quantity': 'الكمية غير صحيحة',
    'please_wait': 'يرجى الانتظار',
    'add_product_to_cart_error': 'تعذر إضافة المنتج إلى السلة',
    'customer': 'العميل',
    'number_copied': 'تم نسخ الرقم',
    'call_unavailable': 'لا يمكن إجراء المكالمة',
    'address_copied': 'تم نسخ العنوان',
    'maps_open_error': 'تعذر فتح الخرائط',
    'payment_status_colon': 'حالة الدفع: ',
    'paid': 'مدفوع',
    'unpaid': 'غير مدفوع',
    'payment_failed': 'فشل الدفع',
    'receive_order': 'استلام الطلب',
    'order_claimed_success': 'تم استلام الطلب للتوصيل بنجاح',
    'order_delivered_success': 'تم تسليم الطلب بنجاح',
    'not_specified': 'غير محدد',
    'product': 'منتج',
    'view_details_and_receive': 'عرض التفاصيل والاستلام',
    'delivered_orders_count': '{count} طلب تم تسليمه',
    'skip': 'تخطي',
    'next': 'التالي',
    'start_shopping_now': 'ابدأ بالتسوق الآن',
    'splash_tagline': 'جودة تستحقها.. أسعار تناسبك',
    'track_order_dynamic': 'تتبع الطلب #{number}',
};

  static const _en = {
    // General
    'app_name': 'BHM Supermarket',
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'edit': 'Edit',
    'close': 'Close',
    'confirm': 'Confirm',
    'search': 'Search',
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'no_data': 'No data',
    'retry': 'Retry',
    // Auth
    'login': 'Login',
    'logout': 'Logout',
    'register': 'Register',
    'phone': 'Phone Number',
    'email': 'Email',
    'password': 'Password',
    'login_with_phone': 'Login with Phone',
    'login_with_email': 'Login with Email',
    'otp_title': 'Verification Code',
    'otp_sent_phone': 'Code sent to',
    'otp_sent_email': 'Code sent to your email',
    'resend': 'Resend',
    'no_account': 'No account?',
    // Home
    'home': 'Home',
    'categories': 'Categories',
    'cart': 'Cart',
    'profile': 'Profile',
    'favorites': 'Favorites',
    'orders': 'Orders',
    'notifications': 'Notifications',
    // Product
    'add_to_cart': 'Add to Cart',
    'add_to_favorites': 'Add to Favorites',
    'remove_from_favorites': 'Remove from Favorites',
    'unit': 'Unit',
    'price': 'Price',
    'quantity': 'Quantity',
    'in_stock': 'In Stock',
    'out_of_stock': 'Out of Stock',
    'select_unit': 'Select Unit',
    // Cart
    'cart_empty': 'Cart is Empty',
    'subtotal': 'Subtotal',
    'delivery_fee': 'Delivery Fee',
    'total': 'Total',
    'checkout': 'Checkout',
    'clear_cart': 'Clear Cart',
    // Checkout
    'delivery_address': 'Delivery Address',
    'payment_method': 'Payment Method',
    'coupon': 'Discount Coupon',
    'place_order': 'Place Order',
    'order_summary': 'Order Summary',
    // Orders
    'order_number': 'Order Number',
    'order_status': 'Status',
    'track_order': 'Track Order',
    // Address
    'add_address': 'Add Address',
    'delivery_addresses': 'Delivery Addresses',
    'default_address': 'Default',
    // Admin
    'manage_products': 'Manage Products',
    'manage_orders': 'Manage Orders',
    'manage_users': 'Manage Users',
    'manage_delivery': 'Manage Delivery',
    'reports': 'Reports',
    'total_sales': 'Total Sales',
    'total_orders': 'Total Orders',
    'active_users': 'Active Users',
    'pending_orders': 'Pending Orders',
    // Delivery
    'my_deliveries': 'My Deliveries',
    'current_order': 'Current Order',
    'delivery_history': 'Delivery History',
    'start_delivery': 'Start Delivery',
    'complete_delivery': 'Complete Delivery',
    // Settings
    'settings': 'Settings',
    'dark_mode': 'Dark Mode',
    'language': 'Language',
    'arabic': 'Arabic',
    'english': 'English',
    // Info
    'about_us': 'About Us',
    'contact_us': 'Contact Us',
    'faq': 'FAQ',
    'privacy_policy': 'Privacy Policy',
    'terms': 'Terms of Use',
    'added_to_cart': 'was added to the cart',
    'appearance': 'Appearance',
    'account': 'Account',
    'information': 'Information',
    'app_version': 'App Version',
    'enabled': 'Enabled',
    'disabled': 'Disabled',
    'delivery_driver': 'Delivery Driver',
    'loading_products': 'Loading products...',
    'products_load_error_title': 'Unable to load products',
    'network_retry': 'Check your internet connection and try again',
    'no_products': 'No products available',
    'products_coming_soon': 'Products will be added soon',
    'products_refresh_stale': 'Could not refresh products — showing previous data',
    'refresh': 'Refresh',
    'hello': 'Hello',
    'guest': 'Guest',
    'search_product_hint': 'Search for any product...',
    'reports_load_error': 'Unable to load reports',
    'system_summary': 'System Summary',
    'from_date': 'From date',
    'to_date': 'To date',
    'customers': 'Customers',
    'locations': 'Locations',
    'pending': 'Pending',
    'confirmed': 'Confirmed',
    'processing': 'Processing',
    'shipped': 'Shipped',
    'delivered': 'Delivered',
    'cancelled': 'Cancelled',
    'orders_value': 'Orders Value',
    'drivers_performance': 'Drivers Performance',
    'no_driver_data': 'No driver data',
    'view_details': 'View Details',
    'cart_changed_coupon': 'Cart contents changed. Please revalidate the coupon.',
    'coupon_expired': 'Coupon expired',
    'please_wait_order': 'Please wait until the order is submitted...',
    'change_or_add_address': 'Change or add address',
    'no_address': 'No address',
    'add_delivery_address_hint': 'Add a delivery address to complete the order',
    'add_delivery_address': 'Add delivery address',
    'enter_coupon': 'Enter coupon code',
    'apply': 'Apply',
    'cart_changed_reapply_coupon': 'Cart total changed. Reapply the coupon to validate the discount.',
    'order_details': 'Order Details',
    'payment_status': 'Payment Status',
    'address': 'Address',
    'notes': 'Notes',
    'gift': 'Gift',
    'product_unavailable': 'Product unavailable',
    'unknown': 'Unknown',
    'coupon_discount': 'Coupon Discount',
    'no_orders': 'No orders',
    'loading_orders': 'Loading orders...',
    'no_notifications': 'No notifications',
    'no_notifications_current': 'No notifications currently',
    'barcode_scanner': 'Barcode Scanner',
    'point_camera_barcode': 'Point the camera at the product barcode',
    'searching_product': 'Searching for product...',
    'enter_barcode_manual': 'Enter barcode manually',
    'search_product': 'Search for product',
    'scanner_camera_error': 'Unable to start the scanner camera. You can enter the barcode manually.',
    'increase_quantity': 'Increase quantity',
    'decrease_quantity': 'Decrease quantity',
    'no_units_product': 'No units are linked to this product yet.',
    'product_unavailable_purchase': 'This product is currently unavailable for purchase',
    'favorites_empty': 'Favorites is empty',
    'clear_cart_confirm': 'Do you want to remove all products?',
    'logout_confirm': 'Are you sure you want to log out?',
    'no_addresses': 'No addresses',
    'add_first_address': 'Add your first address to complete the order',
    'delete_address': 'Delete address',
    'delete_address_confirm': 'Delete this address permanently?',
    'address_deleted': 'Address deleted successfully',
    'address_delete_failed': 'Failed to delete address, try again',
    'set_default': 'Set as default',
    'address_name': 'Address name',
    'edit_address': 'Edit address',
    'password_required': 'Password is required',
    'smart_shopping_tagline': 'Smart shopping • Fast delivery',
    'welcome_login': 'Welcome! Sign in to continue',
    'show_password': 'Show password',
    'hide_password': 'Hide password',
    'create_account_new': 'Create a new account',
    'register_subtitle': 'Enter your details to create an account and start shopping',
    'confirm_password_required': 'Password confirmation is required',
    'passwords_mismatch': 'Passwords do not match',
    'full_name': 'Full name',
    'confirm_password': 'Confirm password',
    'loading_cart': 'Loading cart...',
    'cart_load_error': 'Unable to load cart',
    'clear': 'Clear',
    'add_products_home': 'Add products from the home page',
    'shop_now': 'Shop now',
    'total_products': 'Total products',
    'continue_checkout': 'Continue to checkout',
    'free_gift': 'Free gift',
    'loading_categories': 'Loading categories...',
    'categories_load_error': 'Unable to load categories',
    'no_categories': 'No categories',
    'categories_coming_soon': 'Categories will be added soon',
    'offers': 'Offers',
    'order_notes': 'Order notes',
    'order_notes_hint': 'Write any notes about the order...',
    'delivery_fee_at_order': 'Determined when the order is created',
    'final_total_in_details': 'The final total will be shown in order details',
    'my_earnings': 'My earnings',
    'today': 'Today',
    'week': 'Week',
    'month': 'Month',
    'deliveries': 'Deliveries',
    'last_7_days': 'Last 7 days',
    'history': 'History',
    'order_updated': 'Order updated',
    'confirmed_status': 'Confirmed',
    'out_for_delivery': 'Out for delivery',
    'unspecified': 'Unspecified',
    'delivered_feminine': 'Delivered',
    'cancelled_feminine': 'Cancelled',
    'no_delivery_history': 'No delivery history',
    'new_order': 'New order',
    'new_order_available': 'A new delivery order is available',
    'new_orders_available': 'New delivery orders are available',
    'driver': 'Driver',
    'available_orders': 'Available orders',
    'no_available_orders': 'No available orders currently',
    'no_active_deliveries': 'You have no active deliveries',
    'hello_user': 'Hello, {name}',
    'order': 'Order',
    'addresses': 'Addresses',
    'support_info': 'Support & Information',
    'logout_confirm_account': 'Do you want to log out of your account?',
    'exit': 'Exit',
    'current_stage': 'Current stage',
    'order_cancelled': 'Order cancelled',
    'search_error': 'Unable to perform search',
    'loading_product': 'Loading product...',
    'product_load_error': 'Unable to load product',
    'best_price': 'Best price',
    'item_number': 'Item number',
    'unit_barcode': 'Unit barcode',
    'category': 'Category',
    'status': 'Status',
    'product_description': 'Product description',
    'quantity_hint': 'You can increase or decrease the quantity',
    'related_products': 'Related products',
    'order_received': 'Your order has been received! 🎉',
    'order_contact_hint': 'We will contact you to confirm your order and arrange delivery',
    'what_happens_now': 'What happens now?',
    'store_receives_order': 'The store receives your order',
    'preparing_products': 'Your products are being prepared',
    'delivery_to_door': 'Delivery to your door',
    'back_home': 'Back to home',
    'select_location_confirm': 'Select your location, then tap confirm',
    'selected_map_location': 'Location selected on map',
    'choose_location': 'Choose location',
    'resolving_address': 'Resolving address...',
    'confirm_location': 'Confirm location',
    'see_coupons_offers': 'See coupons and offers',
    'unit_not_selected': 'No unit selected',
    'generic_error': 'Something went wrong, please try again',
    'sort_default': 'Default sorting',
    'price_low_high': 'Price: Low to high',
    'price_high_low': 'Price: High to low',
    'name': 'Name',
    'search_in_category': 'Search in category',
    'offers_load_error': 'Unable to load offers',
    'no_offers': 'No offers',
    'pull_more_offers': 'Pull up to find more offers',
    'no_products_category': 'No products in this category currently',
    'no_data_available': 'No data available currently',
    'added_product_dynamic': '{product} was added',
    'discount': 'Discount',
    'order_number_dynamic': 'Order #{number}',
    'order_number_dynamic2': 'Order number: {number}',
    'order_number_widget': 'Order number: #{number}',
    'product_added_dynamic': '{product} × {quantity} was added to the cart',
    'products': 'Products',
    'sales': 'Sales',
    'special_offer': 'Special offer',
    'invalid_coupon': 'Invalid coupon',
    'coupon_applied': 'Coupon applied ✓',
    'coupon_applied_dynamic': 'Coupon applied, discount {amount} YER',
    'order_create_failed': 'Failed to create order, please try again',
    'order_submit_failed': 'Failed to submit order',
    'order_submit_error': 'An error occurred while submitting the order, please try again',
    'default': 'Default',
    'choose_location_map': 'Choose location from map',
    'default_address_title': 'Default address',
    'favorites_load_error': 'Unable to load favorites',
    'favorites_hint': 'Tap the heart on a product to add it here',
    'search_product_hint_short': 'Search for a product...',
    'search_product_or_barcode': 'Try searching by product name or barcode.',
    'start_search': 'Start typing a product name',
    'search_by_name_barcode_category': 'You can search by name, barcode, or category',
    'clear_all': 'Clear all',
    'search_product_short': 'Search for a product',
    'no_results': 'No results',
    'no_search_results_query': 'No results found for "{query}"\nTry another name, barcode, or category.',
    'favorites_load_error_retry': 'Unable to load favorites. Please try again.',
    'loading_favorites': 'Loading favorites...',
    'favorites_added_count': '{count} products were added to the cart',
    'move_all_to_cart': 'Move all to cart',
    'search_error_retry': 'Unable to perform search. Please try again.',
    'updating_cart': 'Updating...',
    'cart_updated': 'Cart updated',
    'products_load_error': 'An error occurred while loading products',
    'available_orders_load_error': 'Unable to load available orders',
    'my_deliveries_load_error': 'Unable to load your deliveries',
    'deliveries_refresh_error': 'Unable to refresh deliveries',
    'action_in_progress': 'An action is already in progress',
    'claim_order_error': 'Unable to claim the order',
    'order_status_update_error': 'Unable to update order status',
    'order_details_load_error': 'Unable to load order details',
    'invalid_updated_order_data': 'Updated order data is invalid',
    'invalid_order_data': 'Order data is invalid',
    'invalid_barcode': 'Please enter a valid barcode',
    'no_product_for_barcode': 'No product is linked to barcode: {barcode}',
    'no_unit_for_barcode': 'No unit is linked to barcode: {barcode}',
    'product_search_error_retry': 'An error occurred while searching for the product. Please try again.',
    'no_product_for_barcode_generic': 'No product was found for this barcode',
    'orders_load_error_retry': 'Unable to load orders. Please try again.',
    'categories_load_error_retry': 'Unable to load categories. Please try again.',
    'ads_load_error': 'An error occurred while loading ads',
    'products_load_error_retry': 'Unable to load products. Please try again.',
    'login_required_action': 'You must log in to complete this action.',
    'add_address_error': 'Failed to add address',
    'edit_address_error': 'Failed to edit address',
    'copy_number': 'Copy number',
    'call': 'Call',
    'copy_address': 'Copy address',
    'open_maps': 'Open maps',
    'app_version_full': 'Al Bayraq Hypermarket v1.0.0',
    'user': 'User',
    'already_have_account': 'Already have an account?  ',
    'scan_barcode': 'Scan barcode',
    'street': 'Street',
    'recent_searches': 'Recent searches',
    'products_count': '{count} products',
    'orders_count': '{count} orders',
    'select_products': 'Select products',
    'selected_count': '{count} selected',
    'select_at_least_one_unit': 'Select at least one unit',
    'confirm_selection_count': 'Confirm selection ({count})',
    'available_units_count': '{count} units available',
    'quantity_value': 'Quantity: {quantity}',
    'cash_payment': 'Cash payment',
    'bank_card_payment': 'Bank card',
    'today_special_offer': 'Special offer today!',
    'today_offer_body': '20% off all dairy products until the end of today.',
    'order_shipped_notification': 'Your order has shipped',
    'order_out_for_delivery_body': 'Your order #1042 is out for delivery now.',
    'login_error_retry': 'Unable to log in. Please try again.',
    'register_error_retry': 'Unable to create account. Please try again.',
    'enter_coupon_first': 'Enter the coupon code first',
    'coupon_validation_error': 'Unable to validate the coupon',
    'cart_must_have_product': 'Add at least one product',
    'order_submission_in_progress': 'An order is already being submitted',
    'invalid_quantity': 'Invalid quantity',
    'please_wait': 'Please wait',
    'add_product_to_cart_error': 'Unable to add the product to the cart',
    'customer': 'Customer',
    'number_copied': 'Number copied',
    'call_unavailable': 'Unable to make the call',
    'address_copied': 'Address copied',
    'maps_open_error': 'Unable to open maps',
    'payment_status_colon': 'Payment status: ',
    'paid': 'Paid',
    'unpaid': 'Unpaid',
    'payment_failed': 'Payment failed',
    'receive_order': 'Receive order',
    'order_claimed_success': 'Order claimed successfully for delivery',
    'order_delivered_success': 'Order delivered successfully',
    'not_specified': 'Not specified',
    'product': 'Product',
    'view_details_and_receive': 'View details and receive',
    'delivered_orders_count': '{count} orders delivered',
    'skip': 'Skip',
    'next': 'Next',
    'start_shopping_now': 'Start shopping now',
    'splash_tagline': 'Quality you deserve.. Prices you love',
    'track_order_dynamic': 'Track order #{number}',
  };
}
